# -*- coding: utf-8 -*-
"""Untitled35.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kN5GG5RlCvYvH1QyYN8EJZb0xsUd4-mS
"""

#Question number 2 soln 1:
n=int(input())
if n%3==0 and n%5==0 and n%7==0:
  print("JugsMugsPugs")
elif n%3==0:
  if n%3==0 and n%5==0:
    print("JugMugs")
  elif n%3==0 and n%7==0:
    print("JugsPugs")
  else:
    print("Jugs")
elif n%5==0:
  if n%5==0 and n%7==0:
    print("MugsPugs")
  else:
    print("Mugs")
else:
  print("Pugs")

